# Generated by Django 4.1.13 on 2025-08-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=100, unique=True)),
                ('cname', models.CharField(max_length=100)),
                ('cpassword', models.CharField(max_length=8)),
                ('cemail', models.EmailField(max_length=254)),
                ('cmob', models.ImageField(max_length=10, upload_to='')),
                ('ccity', models.CharField(max_length=100)),
                ('ccon', models.CharField(max_length=100)),
                ('cstate', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
