# Generated by Django 4.1.13 on 2025-08-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='cmob',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='register',
            name='cpassword',
            field=models.CharField(max_length=100),
        ),
    ]
