# Generated by Django 4.1.13 on 2025-09-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrationapp', '0002_alter_register_cmob_alter_register_cpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=100, unique=True)),
                ('rname', models.CharField(max_length=100)),
                ('remail', models.EmailField(max_length=254)),
                ('rmob', models.CharField(max_length=15)),
                ('rmes', models.TextField(max_length=255)),
            ],
        ),
    ]
