# Generated by Django 4.1.13 on 2025-09-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('paypal', 'PayPal'), ('paypal_pro', 'PayPal Payment Pro'), ('card', 'Credit/Debit Card')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('expiry_date', models.CharField(blank=True, help_text='MM/YYYY', max_length=7, null=True)),
                ('cvc', models.CharField(blank=True, max_length=4, null=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('state', models.CharField(default='Gujarat', max_length=100)),
                ('city', models.CharField(default='Rajkot', max_length=100)),
                ('street_address', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
