# Generated by Django 4.1.13 on 2025-08-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gst',
            field=models.IntegerField(),
        ),
    ]
