# Generated by Django 4.1.13 on 2025-08-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0002_alter_product_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='car_part',
            field=models.ImageField(blank=True, upload_to='photos/car_parts'),
        ),
    ]
