# Generated by Django 4.1.13 on 2025-08-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0003_product_car_part'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='car_part',
            new_name='car_part1',
        ),
        migrations.AddField(
            model_name='product',
            name='car_part2',
            field=models.ImageField(blank=True, upload_to='photos/car_parts'),
        ),
        migrations.AddField(
            model_name='product',
            name='car_part3',
            field=models.ImageField(blank=True, upload_to='photos/car_parts'),
        ),
    ]
