# Generated by Django 4.1.13 on 2025-09-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0004_rename_car_part_product_car_part1_product_car_part2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
