# Generated by Django 4.1.13 on 2025-09-09 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
        ('cartapp', '0002_cart_cid_alter_cart_cart_id_alter_cart_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.order1'),
        ),
    ]
